version: '3'
services:
  postgres:
    image: "postgres:13"
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
volumes:
  database-data: